### ISSUE TITLE
Where does it install gems to?

### ISSUE THREAD

**Issue by IanVaughan** [jf/rbenv-gemset#26]
1. Where to gems get saved to physically?
2. Where should they show up wrt bundle installs?

Create gemset

```
$ echo my-gemset global > .rbenv-gemsets
```

Check empty

```
$ gem list

*** LOCAL GEMS ***

bundler (1.1.4)
```

Install project gems

```
$ bundle install
...
```

Check gemset 

```
$ gem list

*** LOCAL GEMS ***

bundler (1.1.4)
```

Empty?

**Comment by abhilashak** [comment]
You can check here how to activate Gemset using rbenv:
https://abhilashak.com/2017/08/16/rbenv-start-with-new-ruby-and-rails-versions/
