### ISSUE TITLE
Explixitly disable global gemset

### ISSUE THREAD

**Issue by mrhead** [jf/rbenv-gemset#59]
Is it possible to use just local gemset?

I have this issue:

```
[master][~/ruby/notes] rbenv gemset active
.gems global
[master][~/ruby/notes] ll .gems/gems
total 0
drwxr-xr-x   6 head  staff  204 Jan  2 21:36 .
drwxr-xr-x  11 head  staff  374 Jan  2 21:39 ..
drwxr-xr-x  11 head  staff  374 Jan  2 21:36 rspec-core-2.14.6
drwxr-xr-x  10 head  staff  340 Jan  2 21:36 rspec-expectations-2.14.3
drwxr-xr-x  10 head  staff  340 Jan  2 21:36 rspec-mocks-2.14.4
drwxr-xr-x  11 head  staff  374 Jan  2 21:36 rspec-rails-2.14.0
[master][~/ruby/notes] rspec
...
/Users/head/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.5.1/lib/bundler/runtime.rb:34:in `block in setup': You have already activated mime-types 1.25.1, but your Gemfile requires mime-types 1.25. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
```

When I run `bundle install` it writes that everything is installed. But obviously it is installed just in the global gemset.

I think that it should be possible to disable global gemset somehow. `bundle exex rspec`works for me, but I think that goal of using gemsets is to avoid it (and that is my goal).

Or is there some other solution to this issue?

**Comment by dlovellrw** [comment]
My purpose in using rbenv-gemset is to have a clean set of gems in the project directory installed specifically for the project.  My purpose is not to overlay in the project gems additional to some set installed elsewhere (global or otherwise).  **I'm using the @tombell fork.** (In spite of the profane name, which about sums it up anyway.)

You can pick on me for my housecleaning of gemsets in parent directories; but, hey software can be hard enough without having to run down development environment quirks or differences.  The fork allows me to cleanly nail down the gems in use for the project without any fuss or worry.  +1 Thank you, Tom.

**Comment by jf** [comment]
Yup, @dlovellrw. I've remained silent for a long time but... I will work on it this weekend.

**Comment by bekicot** [comment]
Thanks @jf . We appreciate your hard work. 
Keep Up the good work :) .

**Comment by jf** [comment]
So guys, add "-global" to your gemsets file, and you won't have any gems from the "global" gemset anymore. This _may_ become the default for the future, but we'll see....

**Comment by mrentz** [comment]
Err... Excuse me if I'm totally out of my depth here but, what is the purpose of having a local gemset if the "global" set of gems get used anyway?

i.e.  
`$rbenv gemset active`
`tempest`

and then `gem list` lists all of the globally installed gems?

I must be missing something. Sorry if this is not making sense

**Comment by mrentz** [comment]
Oh yes my project specific .rbenv-gemsets file

`tempest`
`-global`

**Comment by jf** [comment]
> @jf Thanks for helping out here.
> 
> I think I'm totally out of my depth here but, what is the purpose of having a local gemset if the "global" set of gems get used anyway?
> 
> i.e.
> `$rbenv gemset active`
> `tempest`
> 
> and then `gem list` lists all of the globally installed gems?
> 
> I must be missing something. Sorry if this is not making sense

hi @mrentz, sorry for the (super!) late reply. I only just noticed this.

To answer your question, you should be using `rbenv-gemset` from the time you install a ruby version. This will ensure that you have everything neatly organized in your gemsets the way you want them.

> Am I going "bonkers"? I can not install any of the gems that are already installed in global.

You actually can. If you temporarily rename your `.rbenv-gemsets` file to something else, you should be able to "gem uninstall" whatever you need out of "global", and then install what you need into separate gemsets.
