### ISSUE TITLE
How to rename or remove gemsets?

### ISSUE THREAD

**Issue by georgeu2000** [jf/rbenv-gemset#75]
How to rename or remove gemsets?

**Comment by jf** [comment]
Hey @georgeu2000, to remove gemsets, you can use `rbenv gemset delete`. There is no "rename" command, at the moment, but I will look into implementing it sometime.

**Comment by georgeu2000** [comment]
Cool. Thanks.

I have been using rbenv-gemset for a few years and love it. Thank you.
