### ISSUE TITLE
`rbenv-gemset` command not found, but `rbenv gemset` works fine

### ISSUE THREAD

**Issue by LukeSwart** [jf/rbenv-gemset#77]
I am not sure if the documentation is up to date, but I didn't have the `rbenv-gemset` command after installing via `git clone git://github.com/jf/rbenv-gemset.git $HOME/.rbenv/plugins/rbenv-gemset` as directed in the documentation. Perhaps the documentation is missing something? I re-sourced my bash file (`source ~/.bashrc`) and re-init my rbenv (`rbenv init`), but still do not have the `rbenv-gemset` command.

After browsing through existing issues, I found issue #43, and it looks like `rbenv gemset` is the command that works for me. But I still don't know if this is the intended command. Perhaps the correct command is `rbenv gemset`, or the documentation is out of date? If not, then some guidance would be appreciated about how to properly install this plugin.

If it helps, I am on Archlinux:
```
[me]/home/lucas$ uname -a
Linux me 4.4.1-1-ARCH #1 SMP PREEMPT Mon Feb 1 08:16:18 CET 2016 x86_64 GNU/Linux
```

**Comment by jf** [comment]
Thanks @LukeSwart for the helpful info. I believe (no time to really dig into the history now) that it has been `rbenv gemset` for some time now. My suspicion is that it became that way from cc575b669 onwards. If anybody was using `rbenv-gemset` before, they really should be using `rbenv gemset` now.

How did you previously install rbenv-gemset?

**Comment by LukeSwart** [comment]
I did the first installation today! I installed according to the documentation on the readme, but the documentation seems a little confusing/sparse for a newbie. I looked at PR #76 which helped a bit, but it refers to `rbenv-gemset` instead of `rbenv gemset`, so that was confusing.

**Comment by jf** [comment]
Wow ok, I see! I've missed that (it's not been accepted just yet, btw); thanks for the info!

**Comment by jf** [comment]
Just to be sure, @LukeSwart: you got `rbenv-gemset` from that PR? Am I correct?

**Comment by LukeSwart** [comment]
@jf Yes, I got it from PR #47
