### ISSUE TITLE
About local.

### ISSUE THREAD

**Issue by netw0rm** [jf/rbenv-gemset#78]
I used the pyenv-virtualenv  command and it has the local command to auto-add a .pyenv-version file.
So, can we add a rbenv-gemset-local command to set a .rbenv-gemset file.

**Comment by jf** [comment]
I am leaning towards simplicity on this one. The `.rbenv-gemsets` file is easy enough to edit. How does the `pyenv-virtualenv` command work? Can you point me to the documentation?

**Comment by netw0rm** [comment]
It used the env as a version,
https://github.com/yyuu/pyenv-virtualenv/blob/master/bin/pyenv-virtualenv,
  and can set it by pyenv local $someenvs .

May be we can set a command rbenv-gemset-local as    echo "$1" >
.rbenv-gemsets    ... or something else...






jf <notifications@github.com>于2016年7月24日周日 下午2:30写道：

**Comment by jf** [comment]
Sorry, but no. Edit the file yourself, or send in a patch to `rbenv gemset init`.
