### ISSUE TITLE
MacOS: "mkdir: /usr/gemsets/{gemset_name}: Operation not permitted"

### ISSUE THREAD

**Issue by bekicot** [jf/rbenv-gemset#88]
Cannot create gemsets while the ruby version used is the one installed by the system.

Possible fix:
Change the path to "/usr/local/share/gemsets"
or
change the error messages to "Can't create gemsets on a ruby version that is not installed by rbenv"

**Comment by jf** [comment]
hi @bekicot sorry for the late reply.

I don't see how the first fix is possible for everybody: does everybody have write access to /usr/local/share? it's current 755 root:wheel right now on my system.

I think the second fix (tell the user that the current ruby isn't one installed or managed by rbenv) is possible. Would you be able to submit a patch for this?

**Comment by bekicot** [comment]
> I don't see how the first fix is possible for everybody: does everybody have write access to /usr/local/share? it's currently 755 root:wheel right now on my system.

I was dumb. I didn't check the permission. [Filesystem Hierarchy Standard](http://www.pathname.com/fhs/pub/fhs-2.3.pdf) also suggest the content of the directory should be static. 

> I think the second fix (tell the user that the current ruby isn't one installed or managed by rbenv) is possible. Would you be able to submit a patch for this?

Sure, I'm happy to do that.

**Comment by jf** [comment]
Actually, before I accept #90: how did you get this error in the first place? What did you do?

**Comment by bekicot** [comment]
> Actually, before I accept #90: I want to understand a bit more: how did you get this error in the first place? What was the process, what did you do, and how did you get that error?

When I first get this error is when I setup a new computer. After installing Ruby via Rbenv, I didn't set the global gemset. When I run `rbenv gemset init` it shows that error. The error itself wasn't intuitive for me to know that the problem was I'm using ruby installed by system.

**Comment by jf** [comment]
Thanks, that's really good to know. I was initially thinking from your PR #90 that it had something to do with how you called `rbenv gemset create`...

In this case if calling `init` is how you came across the problem, I would rather fix the problem in `init`, than create extra code in `create`. Can you do that?

In the meantime, I've improved the error output for `rbenv gemset create` to not be misleading (`system` should have been taken out of the list, and now it finally is) with 81c5fbfea4378f48249d0ba58f0899d645895d3b
