### ISSUE TITLE
RBenv gemset project file

### ISSUE THREAD

**Issue by JHero23** [jf/rbenv-gemset#89]
So I'm following a tutorial that uses RVM, but they use the command `rvm use --create 2.0.0@training` to create a gemset with the ruby version 2.0.0 for the project "training". I would like to know what is the equivalent command for rbenv gemset? And do you have an example of how to use it before/after making the project?

I know alot of ruby users now use the bundler gem, but now I'm curious as to how to use rbenv-gemsets for research purposes.

Thank you.

**Comment by jf** [comment]
Did you check out the README @JHero23 ? There's a usage section.
