### ISSUE TITLE
Gemset not "hooking" into rbenv version

### ISSUE THREAD

**Issue by angarc** [jf/rbenv-gemset#91]
I'm new to this, so forgive me for some simple mistakes. Following the README hasn't really helped me; I've seen on other issues that there has been some confusion about the README. 

When I used a gemset for RVM, I would see it in the ruby version. I would run:

`rvm gemset create my_cool_app`
` rvm 2.5.1@my_cool_app`

I could also a have a `.ruby-version` file with the gemset in it like this: `2.5.1@my_cool_app`. And it worked perfectly. When I would view my ruby version, it would tell me my version **with** the gemset.

However, that's not happening with this plugin. I followed the README

I ran `rbenv gemset init` in my **Rails project** which created the `.rbenv-gemsets` file. When I ran `rbenv gemset active` it showed my gemset correctly. But when I run:

`rbenv version` in my project, I get this:

`2.6.3 (set by /Users/garcia/.rbenv/version)` 

There is no gemset. It seems like the gemset is there, but it's not doing anything. 

Am I wrongly expecting RVM behavior? Is it actually working fine? 

**Additional Questions**
- Is a `.ruby-version` file necessary with version and gemset in it?

**Comment by jf** [comment]
hi @angarc , apologies for the late reply

> Am I wrongly expecting RVM behavior? Is it actually working fine?

yes, you are. And yes (to both questions). `rbenv-gemset` is **not** rvm

> Is a .ruby-version file necessary with version and gemset in it?

`rbenv-gemset` has its own config file... and `rbenv` has its own.
