### ISSUE TITLE
Precise output of rbenv gemset active

### ISSUE THREAD

**Issue by inopinatus** [jf/rbenv-gemset#92]
Hi there,

The result of `rbenv gemset active` is currently (since 2012) always either:

* a single line of space-separated gemsets to stdout, or
* nothing to stdout, an error message to stderr, and exit code 1.

Please forgive me if I missed it, but I didn't see this specifically documented right now. Would be it be reasonable to assume this specification by tools that consume the output of `rbenv gemset active`?

Thanks!

**Comment by inopinatus** [comment]
For reference the context of this question is https://github.com/ohmyzsh/ohmyzsh/issues/8925

**Comment by jf** [comment]
Hi @inopinatus , apologies for the late reply, but yes. You can assume this.

**Comment by inopinatus** [comment]
Thank you!
