### ISSUE TITLE
add an OSI-approved license

### ISSUE THREAD

**Issue by chenrui333** [jf/rbenv-gemset#93]
While trying to update the homebrew formulae, I found the license text is little bit wild, and I used `Unlicense` to better reflect the intentions of the license, but obviously, it is still not an OSI-approved license, which might cause some confusion down the path.

I think we can pick and choose from the following license moving forward so that we can make sure it is loud and clear :) :
- https://spdx.org/licenses/CC0-1.0.html
- https://spdx.org/licenses/Unlicense.html

relates to https://github.com/Homebrew/homebrew-core/issues/58225#issuecomment-667761517

cc @Rylan12

**Comment by jf** [comment]
I see that "Unlicense" was already stated as the license without this project's approval. Please do not think to speak for `rbenv-gemset`.

**Comment by Rylan12** [comment]
@jf to clarify:

`Unlicense` was added for `rbenv-gemset` as a mistake, but we need to know what the correct license is. In its current state, `rbenv-gemset` doesn't have an acceptable license which means it will likely need to be removed from Homebrew/core in the future. @chenrui333 is suggesting two licenses that would be acceptable for Homebrew and are similar to the "public domain" statement you have on the README.

It's, of course, 100% up to you whether to include one of these or not. Whatever you decide to do will be reflected in Homebrew.

In the meantime, I will remove the `Unlicense` reference in Homebrew as it is incorrect.

**Comment by chenrui333** [comment]
> I see that "Unlicense" was already stated as the license without this project's approval. Please do not think to speak for `rbenv-gemset`.

yeah, that was on me, but I am proposing a way moving forward (making license more clear and distribution more easy to use). Do you mind advising how to move forward? Thanks!
