### ISSUE TITLE
plugin confuses rbenv after rubygems update on jruby

### ISSUE THREAD

**Issue by hurricup** [jf/rbenv-gemset#94]
I have no idea what exactly  is going on, still, removing this plugin fixes things for rbenv. And everything works fine for other version managers as is. Probably it requires fixes on rbenv side, may be both.

Dockerfile for demonstration:
```Dockerfile
FROM ubuntu:20.04

RUN apt update && apt upgrade -y
RUN apt install curl sudo gnupg2 git gcc make -y

# tzdata
RUN sudo bash -c 'export DEBIAN_FRONTEND=noninteractive && \
    ln -fs /usr/share/zoneinfo/Europe/Moscow /etc/localtime && \
    apt-get install -y tzdata && \
    dpkg-reconfigure --frontend noninteractive tzdata'

# install rbenv
RUN git clone https://github.com/rbenv/rbenv.git ~/.rbenv
RUN cd ~/.rbenv && src/configure && make -C src

# install ruby-build
RUN git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build

# install jruby
ENV RUBY_CONFIGURE_OPTS="--disable-install-doc"
ENV MAKEOPTS="-j 8"

# install prerequisties
RUN apt install openjdk-8-jre-headless g++ -y

# install jruby
RUN bash -l -c "~/.rbenv/bin/rbenv install jruby-9.3.2.0"

# install gemset plugin. COMMENTING THIS OUT fixes things
RUN git clone git://github.com/jf/rbenv-gemset.git ~/.rbenv/plugins/rbenv-gemset

# upgrading rubygems
RUN bash -lc "RBENV_VERSION=jruby-9.3.2.0 ~/.rbenv/bin/rbenv exec gem update --system --no-document"

# entry point indicating the bug
CMD bash -lc "RBENV_VERSION=jruby-9.3.2.0 ~/.rbenv/bin/rbenv exec gem env"
```

Run: `docker build -t test_jruby . && docker run --rm -it test_jruby`

**Comment by jf** [comment]
I am open to help you further, but i'm not sure this is an authorized way to install and use rbenv. Have you looked at the instructions at https://github.com/rbenv/rbenv ?

**Comment by hurricup** [comment]
yes. this is the way it used for different automations for a quite some time. And it works perfectly.

**Comment by hurricup** [comment]
Do you know, by any chance, a better way to use rbenv for non-interactive executions?

**Comment by jf** [comment]
> yes. this is the way it used for different automations for a quite some time. And it works perfectly.

if you choose to use the software another way aside from the official instructions, you should know that this means you're sort of on your own. The beauty about this situation though is that what you're using is open source, so you can, if you want, look into the source

**Comment by hurricup** [comment]
Well, I'm not sure what are we discussing here. 

I just wanted to let you know that this plugin seems affecting rbenv work in a bad way. Despite on how I'm using it. Everything works fine and as expected without it. 

Feel free to close the issue if you think that everything is fine.

**Comment by hurricup** [comment]
Btw, according to this: https://github.com/rbenv/rbenv/wiki/How-to-edit-path

All we need is to set RBENV_VERSION and runs shim, and we do. But shim for some reason is not resolved/resolved incorrectly (depending on existence of other executable with the same name)

**Comment by jf** [comment]
this is not a supported way to do things. Everything *is* fine, actually. You're just doing things the wrong way. I wish you would look at https://github.com/rbenv/rbenv#installation and that would give you some clues as to what to do.

The tricky bit here is dealing with `.bashrc` vs `.bash_profile`. I will give you a clue, and you should hopefully be able to figure it out for your non-interactive use case: set your PATH in `.bash_profile`, and run the commands you need for setup in `.bash_profile` as well. Once that's done, you will be able to use `rbenv` the way it was designed to: `bash -lc "gem env"` !

**Comment by jf** [comment]
> Btw, according to this: https://github.com/rbenv/rbenv/wiki/How-to-edit-path
> 
> All we need is to set RBENV_VERSION and runs shim, and we do. But shim for some reason is not resolved/resolved incorrectly (depending on existence of other executable with the same name). You may run the command `RBENV_VERSION=jruby-9.3.2.0 ~/.rbenv/shims/jgem env`

this tells you to actually add the shims directory to your PATH. But you'e not doing that and choosing to skip past that because you think you just need to be able to reach the first binary you want/need the first time by calling it directly. This may work for certain binaries and certain situations.. but not all the time

**Comment by hurricup** [comment]
Adding shims directory to the PATH doesn't help of course.

**Comment by hurricup** [comment]
The key difference is existence of shims directory without `~`, with interpolated `$HOME`. 
Still unclear why plugin presence affects this.

**Comment by hurricup** [comment]
Thanks for your thoughts on the matter, it was really helpful. Again, feel free to close this one if you don't think it's a problem.

**Comment by jf** [comment]
to be clear, I have looked at your Dockerfile, and have also been able to demonstrate on my own system that there is absolutely no issue at all. You just (as I've mentioned several times) need to install and use rbenv properly, as per their instructions, and not do any sort of hack.

I'm hoping that my pointing you to the instructions for `rbenv`, **plus** my hint, should be able to help you resolve your problem with the Dockerfile and allow you to run jruby properly. There is issue, neither with `rbenv`, or with `rbenv-gemset`.

**Comment by hurricup** [comment]
Yes, thanks again, I've solved my problem. 
If you don't think that inconsistent behavior with and without plugin is ok with such usage, then close this one for sure.

**Comment by jf** [comment]
you would be wrong if you say that without the plugin, jruby is in the PATH. No way. I am closing this.

**Comment by hurricup** [comment]
I don't need to say anything. Docerfile above illustrates this. Commenting out gemset plugin makes it work.

**Comment by hurricup** [comment]
> you would be wrong if you say that without the plugin, jruby is in the PATH. No way. I am closing this.

see https://github.com/rbenv/rbenv/blob/master/libexec/rbenv-exec#L45

**Comment by jf** [comment]
> > you would be wrong if you say that without the plugin, jruby is in the PATH. No way. I am closing this.
> 
> see https://github.com/rbenv/rbenv/blob/master/libexec/rbenv-exec#L45

ok. That's a good discovery. I think there was a miscommunication here. `rbenv` updates *its own PATH*; but it does NOT update *your* PATH in the shell.j

ALSO: https://github.com/rbenv/rbenv/blob/master/README.md#basic-github-checkout

**Comment by hurricup** [comment]
1. I know how it works, thank you.  
2. Aes, you are right - it's a hacky way.
3. Again - my report about inconsistency. Different behavior. Nothing more. Just fyi.

**Comment by jf** [comment]
> 1. I know how it works, thank you.
> 
>     2. Aes, you are right - it's a hacky way.
> 
>     3. Again - my report about inconsistency. Different behavior. Nothing more. Just fyi.
> 
>     4. I never said that command set up my shell or smth. I said this command does work with bare rbenv and doesnt with gemset plugin.

ok. Noted. Thanks.

**Comment by hurricup** [comment]
You may run image above with `RBENV_DEBUG`  set, with and without a plugin and compare logs. This is how I found this inconsistency, but there is too much happening for me to fix this.

**Comment by jf** [comment]
FYI @hurricup if you check out the `bulletproof_exec_path` branch for `rbenv-gemset`, you will find that it will work with your Dockerfile. I would consider this an early preview, but I believe the code should not break anything else. You can try it out.

**Comment by hurricup** [comment]
Thank you!

**Comment by jf** [comment]
hi @hurricup, it's been a while, but FYI I've brought the change over to the master branch. Feel free to use the master branch from now on!
