### ISSUE TITLE
Clean up copy and paste code in README

### ISSUE THREAD

**Issue by datadaveshin** [jf/rbenv-gemset#98]
There are one-line commands in the README that have a `$` prompt in them, which carry over when using the "copy" button, raising the `command not found: $` message in the terminal. Minor, but thought I'd mention it and send a PR for your consideration.

Also, I thought maybe:
`$ RBENV_GEMSET_FILE="$HOME/hplabs/project1/.rbenv-gemsets" rails new newproject`
could be:
`RBENV_GEMSET_FILE="$HOME/<your-username>/<projects-directory>/.rbenv-gemsets" rails new <newproject>`
but since it's in the neckbeard section, I just removed the first `$`.

**Comment by jf** [comment]
Closing in lieu of comments at #99
